name: Codacy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Run Coverage and Send to Codacy
      run: npm run coverage-to-codacy
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    - name: Check Coverage Grade
      run: |
        grade=$(curl -s -X GET "https://api.codacy.com/2.0/project" \
          -H 'Accept: application/json' \
          -H "project_token: ${{ secrets.CODACY_PROJECT_TOKEN }}" | jq -r '.commit.commit.grade')
        echo "Coverage Grade: $grade"
        if [[ "$grade" == "A" ]]; then
          echo -e "\e[1;42m Grade $grade is ok. Build will continue. \e[0m"
        else
          echo -e "\e[1;31m Grade $grade is below the expected and the build will stop. \e[0m"
          exit 1
        fi
      env:
        CI: true
