name: Codacy Analysis

on: [push, pull_request]

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v3
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
